# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AddFlutterToExistingIOSApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddFlutterToExistingIOSApp
  pod 'FLEX'
  flutter_application_path = '/Users/admin/Documents/App Development /Flutter Development/Git-Flutter-Examples'

  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
